// Base de dados: campeões da UEFA Champions League (era 1992/93–2023/24)
// Escalações titulares reais de cada final. Ratings são estimativas para o jogo.
const CHAMPIONS = [
  {
    year: 1993, club: "Olympique de Marseille", country: "França",
    opponent: "AC Milan", score: "1-0", colors: ["#1a5fb4", "#ffffff"],
    players: [
      { name: "Fabien Barthez", pos: "GK", rating: 84 },
      { name: "Jocelyn Angloma", pos: "DEF", rating: 78 },
      { name: "Marcel Desailly", pos: "DEF", rating: 88 },
      { name: "Basile Boli", pos: "DEF", rating: 80 },
      { name: "Eric Di Meco", pos: "DEF", rating: 76 },
      { name: "Didier Deschamps", pos: "MID", rating: 85 },
      { name: "Franck Sauzée", pos: "MID", rating: 82 },
      { name: "Christophe Dugarry", pos: "MID", rating: 80 },
      { name: "Abedi Pelé", pos: "MID", rating: 83 },
      { name: "Rudi Völler", pos: "FWD", rating: 87 },
      { name: "Alen Bokšić", pos: "FWD", rating: 82 },
    ],
  },
  {
    year: 1994, club: "AC Milan", country: "Itália",
    opponent: "Barcelona", score: "4-0", colors: ["#fb090b", "#000000"],
    players: [
      { name: "Sebastiano Rossi", pos: "GK", rating: 80 },
      { name: "Mauro Tassotti", pos: "DEF", rating: 82 },
      { name: "Franco Baresi", pos: "DEF", rating: 92 },
      { name: "Alessandro Costacurta", pos: "DEF", rating: 85 },
      { name: "Paolo Maldini", pos: "DEF", rating: 94 },
      { name: "Demetrio Albertini", pos: "MID", rating: 86 },
      { name: "Zvonimir Boban", pos: "MID", rating: 87 },
      { name: "Marcel Desailly", pos: "MID", rating: 88 },
      { name: "Dejan Savićević", pos: "MID", rating: 88 },
      { name: "Daniele Massaro", pos: "FWD", rating: 83 },
      { name: "Jean-Pierre Papin", pos: "FWD", rating: 87 },
    ],
  },
  {
    year: 1995, club: "Ajax", country: "Holanda",
    opponent: "AC Milan", score: "1-0", colors: ["#d2122e", "#ffffff"],
    players: [
      { name: "Edwin van der Sar", pos: "GK", rating: 89 },
      { name: "Michael Reiziger", pos: "DEF", rating: 83 },
      { name: "Danny Blind", pos: "DEF", rating: 84 },
      { name: "Frank de Boer", pos: "DEF", rating: 87 },
      { name: "Sonny Silooy", pos: "DEF", rating: 76 },
      { name: "Edgar Davids", pos: "MID", rating: 88 },
      { name: "Ronald de Boer", pos: "MID", rating: 84 },
      { name: "Clarence Seedorf", pos: "MID", rating: 87 },
      { name: "Finidi George", pos: "MID", rating: 81 },
      { name: "Patrick Kluivert", pos: "FWD", rating: 86 },
      { name: "Jari Litmanen", pos: "FWD", rating: 87 },
    ],
  },
  {
    year: 1996, club: "Juventus", country: "Itália",
    opponent: "Ajax", score: "1-1 (pen)", colors: ["#000000", "#ffffff"],
    players: [
      { name: "Angelo Peruzzi", pos: "GK", rating: 84 },
      { name: "Moreno Torricelli", pos: "DEF", rating: 78 },
      { name: "Ciro Ferrara", pos: "DEF", rating: 84 },
      { name: "Paolo Montero", pos: "DEF", rating: 83 },
      { name: "Sergio Porrini", pos: "DEF", rating: 77 },
      { name: "Didier Deschamps", pos: "MID", rating: 86 },
      { name: "Paulo Sousa", pos: "MID", rating: 83 },
      { name: "Antonio Conte", pos: "MID", rating: 82 },
      { name: "Alessio Tacchinardi", pos: "MID", rating: 78 },
      { name: "Alessandro Del Piero", pos: "FWD", rating: 88 },
      { name: "Fabrizio Ravanelli", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 1997, club: "Borussia Dortmund", country: "Alemanha",
    opponent: "Juventus", score: "3-1", colors: ["#fde100", "#000000"],
    players: [
      { name: "Stefan Klos", pos: "GK", rating: 80 },
      { name: "Jürgen Kohler", pos: "DEF", rating: 85 },
      { name: "Matthias Sammer", pos: "DEF", rating: 88 },
      { name: "Julio César", pos: "DEF", rating: 79 },
      { name: "Stefan Reuter", pos: "DEF", rating: 80 },
      { name: "Paulo Sousa", pos: "MID", rating: 83 },
      { name: "Paul Lambert", pos: "MID", rating: 78 },
      { name: "Andreas Möller", pos: "MID", rating: 85 },
      { name: "Michael Zorc", pos: "MID", rating: 80 },
      { name: "Karl-Heinz Riedle", pos: "FWD", rating: 84 },
      { name: "Stéphane Chapuisat", pos: "FWD", rating: 82 },
    ],
  },
  {
    year: 1998, club: "Real Madrid", country: "Espanha",
    opponent: "Juventus", score: "1-0", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Bodo Illgner", pos: "GK", rating: 82 },
      { name: "Christian Panucci", pos: "DEF", rating: 83 },
      { name: "Fernando Hierro", pos: "DEF", rating: 88 },
      { name: "Manuel Sanchís", pos: "DEF", rating: 81 },
      { name: "Roberto Carlos", pos: "DEF", rating: 89 },
      { name: "Clarence Seedorf", pos: "MID", rating: 87 },
      { name: "Fernando Redondo", pos: "MID", rating: 87 },
      { name: "Christian Karembeu", pos: "MID", rating: 79 },
      { name: "Raúl", pos: "MID", rating: 89 },
      { name: "Predrag Mijatović", pos: "FWD", rating: 84 },
      { name: "Fernando Morientes", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 1999, club: "Manchester United", country: "Inglaterra",
    opponent: "Bayern Munich", score: "2-1", colors: ["#da291c", "#ffe500"],
    players: [
      { name: "Peter Schmeichel", pos: "GK", rating: 90 },
      { name: "Gary Neville", pos: "DEF", rating: 82 },
      { name: "Jaap Stam", pos: "DEF", rating: 89 },
      { name: "Ronny Johnsen", pos: "DEF", rating: 79 },
      { name: "Denis Irwin", pos: "DEF", rating: 81 },
      { name: "David Beckham", pos: "MID", rating: 88 },
      { name: "Roy Keane", pos: "MID", rating: 89 },
      { name: "Nicky Butt", pos: "MID", rating: 78 },
      { name: "Ryan Giggs", pos: "MID", rating: 88 },
      { name: "Dwight Yorke", pos: "FWD", rating: 86 },
      { name: "Andy Cole", pos: "FWD", rating: 84 },
    ],
  },
  {
    year: 2000, club: "Real Madrid", country: "Espanha",
    opponent: "Valencia", score: "3-0", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Iker Casillas", pos: "GK", rating: 88 },
      { name: "Michel Salgado", pos: "DEF", rating: 82 },
      { name: "Fernando Hierro", pos: "DEF", rating: 88 },
      { name: "Iván Campo", pos: "DEF", rating: 80 },
      { name: "Roberto Carlos", pos: "DEF", rating: 89 },
      { name: "Steve McManaman", pos: "MID", rating: 83 },
      { name: "Fernando Redondo", pos: "MID", rating: 87 },
      { name: "Aitor Karanka", pos: "MID", rating: 76 },
      { name: "Guti", pos: "MID", rating: 84 },
      { name: "Raúl", pos: "FWD", rating: 89 },
      { name: "Nicolas Anelka", pos: "FWD", rating: 83 },
    ],
  },
  {
    year: 2001, club: "Bayern Munich", country: "Alemanha",
    opponent: "Valencia", score: "1-1 (pen)", colors: ["#dc052d", "#0066b2"],
    players: [
      { name: "Oliver Kahn", pos: "GK", rating: 92 },
      { name: "Bixente Lizarazu", pos: "DEF", rating: 85 },
      { name: "Samuel Kuffour", pos: "DEF", rating: 79 },
      { name: "Thomas Linke", pos: "DEF", rating: 78 },
      { name: "Willy Sagnol", pos: "DEF", rating: 80 },
      { name: "Stefan Effenberg", pos: "MID", rating: 87 },
      { name: "Jens Jeremies", pos: "MID", rating: 78 },
      { name: "Mehmet Scholl", pos: "MID", rating: 83 },
      { name: "Hasan Salihamidžić", pos: "MID", rating: 80 },
      { name: "Giovane Élber", pos: "FWD", rating: 84 },
      { name: "Carsten Jancker", pos: "FWD", rating: 79 },
    ],
  },
  {
    year: 2002, club: "Real Madrid", country: "Espanha",
    opponent: "Bayer Leverkusen", score: "2-1", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Iker Casillas", pos: "GK", rating: 88 },
      { name: "Michel Salgado", pos: "DEF", rating: 82 },
      { name: "Iván Helguera", pos: "DEF", rating: 82 },
      { name: "Fernando Hierro", pos: "DEF", rating: 88 },
      { name: "Roberto Carlos", pos: "DEF", rating: 89 },
      { name: "Steve McManaman", pos: "MID", rating: 83 },
      { name: "Claude Makélélé", pos: "MID", rating: 87 },
      { name: "Zinedine Zidane", pos: "MID", rating: 96 },
      { name: "Luís Figo", pos: "MID", rating: 91 },
      { name: "Raúl", pos: "FWD", rating: 89 },
      { name: "Fernando Morientes", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 2003, club: "AC Milan", country: "Itália",
    opponent: "Juventus", score: "0-0 (pen)", colors: ["#fb090b", "#000000"],
    players: [
      { name: "Dida", pos: "GK", rating: 85 },
      { name: "Cafu", pos: "DEF", rating: 88 },
      { name: "Alessandro Nesta", pos: "DEF", rating: 91 },
      { name: "Paolo Maldini", pos: "DEF", rating: 94 },
      { name: "Kakha Kaladze", pos: "DEF", rating: 80 },
      { name: "Andrea Pirlo", pos: "MID", rating: 90 },
      { name: "Gennaro Gattuso", pos: "MID", rating: 85 },
      { name: "Clarence Seedorf", pos: "MID", rating: 87 },
      { name: "Rui Costa", pos: "MID", rating: 85 },
      { name: "Filippo Inzaghi", pos: "FWD", rating: 85 },
      { name: "Andriy Shevchenko", pos: "FWD", rating: 91 },
    ],
  },
  {
    year: 2004, club: "FC Porto", country: "Portugal",
    opponent: "AS Monaco", score: "3-0", colors: ["#003366", "#ffffff"],
    players: [
      { name: "Vítor Baía", pos: "GK", rating: 85 },
      { name: "Paulo Ferreira", pos: "DEF", rating: 81 },
      { name: "Ricardo Carvalho", pos: "DEF", rating: 86 },
      { name: "Jorge Costa", pos: "DEF", rating: 82 },
      { name: "Nuno Valente", pos: "DEF", rating: 78 },
      { name: "Costinha", pos: "MID", rating: 82 },
      { name: "Maniche", pos: "MID", rating: 83 },
      { name: "Deco", pos: "MID", rating: 88 },
      { name: "Pedro Mendes", pos: "MID", rating: 78 },
      { name: "Derlei", pos: "FWD", rating: 80 },
      { name: "Carlos Alberto", pos: "FWD", rating: 78 },
    ],
  },
  {
    year: 2005, club: "Liverpool", country: "Inglaterra",
    opponent: "AC Milan", score: "3-3 (pen)", colors: ["#c8102e", "#f6ec19"],
    players: [
      { name: "Jerzy Dudek", pos: "GK", rating: 81 },
      { name: "Steve Finnan", pos: "DEF", rating: 79 },
      { name: "Jamie Carragher", pos: "DEF", rating: 86 },
      { name: "Sami Hyypiä", pos: "DEF", rating: 85 },
      { name: "Djimi Traoré", pos: "DEF", rating: 74 },
      { name: "Steven Gerrard", pos: "MID", rating: 92 },
      { name: "Xabi Alonso", pos: "MID", rating: 88 },
      { name: "Didi Hamann", pos: "MID", rating: 80 },
      { name: "John Arne Riise", pos: "MID", rating: 80 },
      { name: "Milan Baroš", pos: "FWD", rating: 80 },
      { name: "Luis García", pos: "FWD", rating: 81 },
    ],
  },
  {
    year: 2006, club: "Barcelona", country: "Espanha",
    opponent: "Arsenal", score: "2-1", colors: ["#a50044", "#004d98"],
    players: [
      { name: "Víctor Valdés", pos: "GK", rating: 83 },
      { name: "Oleguer", pos: "DEF", rating: 78 },
      { name: "Carles Puyol", pos: "DEF", rating: 88 },
      { name: "Rafael Márquez", pos: "DEF", rating: 84 },
      { name: "Giovanni van Bronckhorst", pos: "DEF", rating: 82 },
      { name: "Edmílson", pos: "MID", rating: 79 },
      { name: "Deco", pos: "MID", rating: 88 },
      { name: "Mark van Bommel", pos: "MID", rating: 82 },
      { name: "Xavi", pos: "MID", rating: 90 },
      { name: "Ronaldinho", pos: "FWD", rating: 93 },
      { name: "Samuel Eto'o", pos: "FWD", rating: 89 },
    ],
  },
  {
    year: 2007, club: "AC Milan", country: "Itália",
    opponent: "Liverpool", score: "2-1", colors: ["#fb090b", "#000000"],
    players: [
      { name: "Dida", pos: "GK", rating: 85 },
      { name: "Massimo Oddo", pos: "DEF", rating: 79 },
      { name: "Alessandro Nesta", pos: "DEF", rating: 91 },
      { name: "Paolo Maldini", pos: "DEF", rating: 93 },
      { name: "Marek Jankulovski", pos: "DEF", rating: 78 },
      { name: "Gennaro Gattuso", pos: "MID", rating: 85 },
      { name: "Massimo Ambrosini", pos: "MID", rating: 80 },
      { name: "Andrea Pirlo", pos: "MID", rating: 90 },
      { name: "Clarence Seedorf", pos: "MID", rating: 86 },
      { name: "Kaká", pos: "FWD", rating: 92 },
      { name: "Filippo Inzaghi", pos: "FWD", rating: 84 },
    ],
  },
  {
    year: 2008, club: "Manchester United", country: "Inglaterra",
    opponent: "Chelsea", score: "1-1 (pen)", colors: ["#da291c", "#ffe500"],
    players: [
      { name: "Edwin van der Sar", pos: "GK", rating: 87 },
      { name: "Wes Brown", pos: "DEF", rating: 78 },
      { name: "Rio Ferdinand", pos: "DEF", rating: 88 },
      { name: "Nemanja Vidić", pos: "DEF", rating: 88 },
      { name: "Patrice Evra", pos: "DEF", rating: 85 },
      { name: "Park Ji-sung", pos: "MID", rating: 80 },
      { name: "Michael Carrick", pos: "MID", rating: 83 },
      { name: "Paul Scholes", pos: "MID", rating: 88 },
      { name: "Cristiano Ronaldo", pos: "MID", rating: 96 },
      { name: "Wayne Rooney", pos: "FWD", rating: 89 },
      { name: "Carlos Tevez", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 2009, club: "Barcelona", country: "Espanha",
    opponent: "Manchester United", score: "2-0", colors: ["#a50044", "#004d98"],
    players: [
      { name: "Víctor Valdés", pos: "GK", rating: 85 },
      { name: "Dani Alves", pos: "DEF", rating: 87 },
      { name: "Gerard Piqué", pos: "DEF", rating: 86 },
      { name: "Carles Puyol", pos: "DEF", rating: 88 },
      { name: "Sylvinho", pos: "DEF", rating: 78 },
      { name: "Sergio Busquets", pos: "MID", rating: 85 },
      { name: "Xavi", pos: "MID", rating: 91 },
      { name: "Andrés Iniesta", pos: "MID", rating: 92 },
      { name: "Samuel Eto'o", pos: "FWD", rating: 89 },
      { name: "Lionel Messi", pos: "FWD", rating: 97 },
      { name: "Thierry Henry", pos: "FWD", rating: 89 },
    ],
  },
  {
    year: 2010, club: "Inter Milan", country: "Itália",
    opponent: "Bayern Munich", score: "2-0", colors: ["#010e80", "#000000"],
    players: [
      { name: "Júlio César", pos: "GK", rating: 85 },
      { name: "Maicon", pos: "DEF", rating: 87 },
      { name: "Lúcio", pos: "DEF", rating: 87 },
      { name: "Walter Samuel", pos: "DEF", rating: 85 },
      { name: "Cristian Chivu", pos: "DEF", rating: 80 },
      { name: "Esteban Cambiasso", pos: "MID", rating: 84 },
      { name: "Javier Zanetti", pos: "MID", rating: 86 },
      { name: "Thiago Motta", pos: "MID", rating: 82 },
      { name: "Wesley Sneijder", pos: "MID", rating: 89 },
      { name: "Samuel Eto'o", pos: "FWD", rating: 89 },
      { name: "Diego Milito", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 2011, club: "Barcelona", country: "Espanha",
    opponent: "Manchester United", score: "3-1", colors: ["#a50044", "#004d98"],
    players: [
      { name: "Víctor Valdés", pos: "GK", rating: 86 },
      { name: "Dani Alves", pos: "DEF", rating: 88 },
      { name: "Gerard Piqué", pos: "DEF", rating: 87 },
      { name: "Carles Puyol", pos: "DEF", rating: 87 },
      { name: "Éric Abidal", pos: "DEF", rating: 81 },
      { name: "Sergio Busquets", pos: "MID", rating: 86 },
      { name: "Xavi", pos: "MID", rating: 92 },
      { name: "Andrés Iniesta", pos: "MID", rating: 93 },
      { name: "Pedro", pos: "FWD", rating: 84 },
      { name: "Lionel Messi", pos: "FWD", rating: 98 },
      { name: "David Villa", pos: "FWD", rating: 87 },
    ],
  },
  {
    year: 2012, club: "Chelsea", country: "Inglaterra",
    opponent: "Bayern Munich", score: "1-1 (pen)", colors: ["#034694", "#ffffff"],
    players: [
      { name: "Petr Čech", pos: "GK", rating: 88 },
      { name: "Branislav Ivanović", pos: "DEF", rating: 82 },
      { name: "John Terry", pos: "DEF", rating: 87 },
      { name: "David Luiz", pos: "DEF", rating: 82 },
      { name: "Ashley Cole", pos: "DEF", rating: 87 },
      { name: "Frank Lampard", pos: "MID", rating: 88 },
      { name: "John Obi Mikel", pos: "MID", rating: 78 },
      { name: "Ramires", pos: "MID", rating: 80 },
      { name: "Juan Mata", pos: "MID", rating: 85 },
      { name: "Didier Drogba", pos: "FWD", rating: 88 },
      { name: "Salomon Kalou", pos: "FWD", rating: 78 },
    ],
  },
  {
    year: 2013, club: "Bayern Munich", country: "Alemanha",
    opponent: "Borussia Dortmund", score: "2-1", colors: ["#dc052d", "#0066b2"],
    players: [
      { name: "Manuel Neuer", pos: "GK", rating: 91 },
      { name: "Philipp Lahm", pos: "DEF", rating: 90 },
      { name: "Dante", pos: "DEF", rating: 82 },
      { name: "Jérôme Boateng", pos: "DEF", rating: 86 },
      { name: "David Alaba", pos: "DEF", rating: 85 },
      { name: "Bastian Schweinsteiger", pos: "MID", rating: 88 },
      { name: "Javi Martínez", pos: "MID", rating: 84 },
      { name: "Arjen Robben", pos: "MID", rating: 90 },
      { name: "Thomas Müller", pos: "MID", rating: 87 },
      { name: "Franck Ribéry", pos: "MID", rating: 90 },
      { name: "Mario Mandžukić", pos: "FWD", rating: 83 },
    ],
  },
  {
    year: 2014, club: "Real Madrid", country: "Espanha",
    opponent: "Atlético Madrid", score: "4-1", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Iker Casillas", pos: "GK", rating: 87 },
      { name: "Dani Carvajal", pos: "DEF", rating: 83 },
      { name: "Sergio Ramos", pos: "DEF", rating: 90 },
      { name: "Pepe", pos: "DEF", rating: 85 },
      { name: "Fábio Coentrão", pos: "DEF", rating: 80 },
      { name: "Luka Modrić", pos: "MID", rating: 89 },
      { name: "Xabi Alonso", pos: "MID", rating: 87 },
      { name: "Ángel Di María", pos: "MID", rating: 88 },
      { name: "Gareth Bale", pos: "FWD", rating: 89 },
      { name: "Karim Benzema", pos: "FWD", rating: 88 },
      { name: "Cristiano Ronaldo", pos: "FWD", rating: 97 },
    ],
  },
  {
    year: 2015, club: "Barcelona", country: "Espanha",
    opponent: "Juventus", score: "3-1", colors: ["#a50044", "#004d98"],
    players: [
      { name: "Marc-André ter Stegen", pos: "GK", rating: 85 },
      { name: "Dani Alves", pos: "DEF", rating: 87 },
      { name: "Gerard Piqué", pos: "DEF", rating: 87 },
      { name: "Javier Mascherano", pos: "DEF", rating: 85 },
      { name: "Jordi Alba", pos: "DEF", rating: 84 },
      { name: "Sergio Busquets", pos: "MID", rating: 87 },
      { name: "Ivan Rakitić", pos: "MID", rating: 85 },
      { name: "Andrés Iniesta", pos: "MID", rating: 91 },
      { name: "Lionel Messi", pos: "FWD", rating: 98 },
      { name: "Luis Suárez", pos: "FWD", rating: 92 },
      { name: "Neymar", pos: "FWD", rating: 91 },
    ],
  },
  {
    year: 2016, club: "Real Madrid", country: "Espanha",
    opponent: "Atlético Madrid", score: "1-1 (pen)", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Keylor Navas", pos: "GK", rating: 84 },
      { name: "Dani Carvajal", pos: "DEF", rating: 85 },
      { name: "Sergio Ramos", pos: "DEF", rating: 90 },
      { name: "Pepe", pos: "DEF", rating: 84 },
      { name: "Marcelo", pos: "DEF", rating: 87 },
      { name: "Casemiro", pos: "MID", rating: 84 },
      { name: "Toni Kroos", pos: "MID", rating: 89 },
      { name: "Luka Modrić", pos: "MID", rating: 89 },
      { name: "Gareth Bale", pos: "FWD", rating: 88 },
      { name: "Cristiano Ronaldo", pos: "FWD", rating: 96 },
      { name: "Karim Benzema", pos: "FWD", rating: 88 },
    ],
  },
  {
    year: 2017, club: "Real Madrid", country: "Espanha",
    opponent: "Juventus", score: "4-1", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Keylor Navas", pos: "GK", rating: 85 },
      { name: "Dani Carvajal", pos: "DEF", rating: 86 },
      { name: "Sergio Ramos", pos: "DEF", rating: 90 },
      { name: "Raphaël Varane", pos: "DEF", rating: 85 },
      { name: "Marcelo", pos: "DEF", rating: 88 },
      { name: "Casemiro", pos: "MID", rating: 85 },
      { name: "Toni Kroos", pos: "MID", rating: 89 },
      { name: "Luka Modrić", pos: "MID", rating: 90 },
      { name: "Cristiano Ronaldo", pos: "FWD", rating: 96 },
      { name: "Karim Benzema", pos: "FWD", rating: 88 },
      { name: "Isco", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 2018, club: "Real Madrid", country: "Espanha",
    opponent: "Liverpool", score: "3-1", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Keylor Navas", pos: "GK", rating: 85 },
      { name: "Dani Carvajal", pos: "DEF", rating: 86 },
      { name: "Sergio Ramos", pos: "DEF", rating: 90 },
      { name: "Raphaël Varane", pos: "DEF", rating: 86 },
      { name: "Marcelo", pos: "DEF", rating: 87 },
      { name: "Casemiro", pos: "MID", rating: 85 },
      { name: "Toni Kroos", pos: "MID", rating: 89 },
      { name: "Luka Modrić", pos: "MID", rating: 91 },
      { name: "Isco", pos: "FWD", rating: 85 },
      { name: "Karim Benzema", pos: "FWD", rating: 88 },
      { name: "Cristiano Ronaldo", pos: "FWD", rating: 96 },
    ],
  },
  {
    year: 2019, club: "Liverpool", country: "Inglaterra",
    opponent: "Tottenham Hotspur", score: "2-0", colors: ["#c8102e", "#f6ec19"],
    players: [
      { name: "Alisson Becker", pos: "GK", rating: 89 },
      { name: "Trent Alexander-Arnold", pos: "DEF", rating: 85 },
      { name: "Joël Matip", pos: "DEF", rating: 82 },
      { name: "Virgil van Dijk", pos: "DEF", rating: 93 },
      { name: "Andrew Robertson", pos: "DEF", rating: 86 },
      { name: "Fabinho", pos: "MID", rating: 85 },
      { name: "Jordan Henderson", pos: "MID", rating: 84 },
      { name: "Georginio Wijnaldum", pos: "MID", rating: 83 },
      { name: "Mohamed Salah", pos: "FWD", rating: 92 },
      { name: "Roberto Firmino", pos: "FWD", rating: 87 },
      { name: "Sadio Mané", pos: "FWD", rating: 89 },
    ],
  },
  {
    year: 2020, club: "Bayern Munich", country: "Alemanha",
    opponent: "Paris Saint-Germain", score: "1-0", colors: ["#dc052d", "#0066b2"],
    players: [
      { name: "Manuel Neuer", pos: "GK", rating: 90 },
      { name: "Joshua Kimmich", pos: "DEF", rating: 88 },
      { name: "Jérôme Boateng", pos: "DEF", rating: 83 },
      { name: "David Alaba", pos: "DEF", rating: 87 },
      { name: "Alphonso Davies", pos: "DEF", rating: 85 },
      { name: "Leon Goretzka", pos: "MID", rating: 85 },
      { name: "Thiago Alcântara", pos: "MID", rating: 88 },
      { name: "Thomas Müller", pos: "MID", rating: 88 },
      { name: "Serge Gnabry", pos: "FWD", rating: 87 },
      { name: "Robert Lewandowski", pos: "FWD", rating: 94 },
      { name: "Kingsley Coman", pos: "FWD", rating: 85 },
    ],
  },
  {
    year: 2021, club: "Chelsea", country: "Inglaterra",
    opponent: "Manchester City", score: "1-0", colors: ["#034694", "#ffffff"],
    players: [
      { name: "Édouard Mendy", pos: "GK", rating: 85 },
      { name: "Thiago Silva", pos: "DEF", rating: 87 },
      { name: "César Azpilicueta", pos: "DEF", rating: 84 },
      { name: "Antonio Rüdiger", pos: "DEF", rating: 85 },
      { name: "Reece James", pos: "MID", rating: 84 },
      { name: "Ben Chilwell", pos: "MID", rating: 83 },
      { name: "N'Golo Kanté", pos: "MID", rating: 90 },
      { name: "Jorginho", pos: "MID", rating: 84 },
      { name: "Mason Mount", pos: "MID", rating: 83 },
      { name: "Kai Havertz", pos: "FWD", rating: 84 },
      { name: "Timo Werner", pos: "FWD", rating: 83 },
    ],
  },
  {
    year: 2022, club: "Real Madrid", country: "Espanha",
    opponent: "Liverpool", score: "1-0", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Thibaut Courtois", pos: "GK", rating: 90 },
      { name: "Dani Carvajal", pos: "DEF", rating: 85 },
      { name: "Éder Militão", pos: "DEF", rating: 84 },
      { name: "David Alaba", pos: "DEF", rating: 86 },
      { name: "Ferland Mendy", pos: "DEF", rating: 82 },
      { name: "Casemiro", pos: "MID", rating: 87 },
      { name: "Toni Kroos", pos: "MID", rating: 87 },
      { name: "Luka Modrić", pos: "MID", rating: 88 },
      { name: "Federico Valverde", pos: "FWD", rating: 85 },
      { name: "Karim Benzema", pos: "FWD", rating: 91 },
      { name: "Vinícius Júnior", pos: "FWD", rating: 88 },
    ],
  },
  {
    year: 2023, club: "Manchester City", country: "Inglaterra",
    opponent: "Inter Milan", score: "1-0", colors: ["#6cabdd", "#1c2c5b"],
    players: [
      { name: "Ederson", pos: "GK", rating: 88 },
      { name: "Kyle Walker", pos: "DEF", rating: 86 },
      { name: "Rúben Dias", pos: "DEF", rating: 88 },
      { name: "John Stones", pos: "DEF", rating: 84 },
      { name: "Nathan Aké", pos: "DEF", rating: 82 },
      { name: "Rodri", pos: "MID", rating: 89 },
      { name: "Bernardo Silva", pos: "MID", rating: 88 },
      { name: "İlkay Gündoğan", pos: "MID", rating: 86 },
      { name: "Riyad Mahrez", pos: "FWD", rating: 85 },
      { name: "Erling Haaland", pos: "FWD", rating: 91 },
      { name: "Jack Grealish", pos: "FWD", rating: 84 },
    ],
  },
  {
    year: 2024, club: "Real Madrid", country: "Espanha",
    opponent: "Borussia Dortmund", score: "2-0", colors: ["#ffffff", "#febe10"],
    players: [
      { name: "Andriy Lunin", pos: "GK", rating: 82 },
      { name: "Dani Carvajal", pos: "DEF", rating: 84 },
      { name: "Antonio Rüdiger", pos: "DEF", rating: 85 },
      { name: "Nacho Fernández", pos: "DEF", rating: 81 },
      { name: "Ferland Mendy", pos: "DEF", rating: 81 },
      { name: "Federico Valverde", pos: "MID", rating: 87 },
      { name: "Toni Kroos", pos: "MID", rating: 86 },
      { name: "Eduardo Camavinga", pos: "MID", rating: 84 },
      { name: "Rodrygo", pos: "FWD", rating: 86 },
      { name: "Jude Bellingham", pos: "FWD", rating: 89 },
      { name: "Vinícius Júnior", pos: "FWD", rating: 90 },
    ],
  },
];
